### ISSUE TITLE
wen

### ISSUE THREAD

**Issue by zhangtong1234** [SJ1115/Materials-Synthesis-PU-GNN#1]
.

**Comment by SJ1115** [comment]
Oh, I think I missed its script files, so I'll upload it(maybe before next Wednesday). Sorry and Thanks for remind me!!

-----Original Message-----
From: ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2023-07-13 (목) 10:22:54 (GMT+09:00)
Subject: [SJ1115/Materials-Synthesis-PU-GNN] wen (Issue #1)

Blogger, are there specific steps to implement it
